// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20230815131322_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CityName = "Washington DC",
                            CountryName = "United States",
                            Rating = 8,
                            Review = "See important national landmarks"
                        },
                        new
                        {
                            DestinationId = 2,
                            CityName = "London",
                            CountryName = "United Kingdom",
                            Rating = 9,
                            Review = "Lovely valleys and streams"
                        },
                        new
                        {
                            DestinationId = 3,
                            CityName = "Atlanta",
                            CountryName = "United States",
                            Rating = 4,
                            Review = "Hot and muggy!"
                        },
                        new
                        {
                            DestinationId = 4,
                            CityName = "Paris",
                            CountryName = "France",
                            Rating = 9,
                            Review = "Tres bien"
                        },
                        new
                        {
                            DestinationId = 5,
                            CityName = "New York City",
                            CountryName = "United States",
                            Rating = 9,
                            Review = "Top of the rock"
                        },
                        new
                        {
                            DestinationId = 6,
                            CityName = "Boston",
                            CountryName = "United States",
                            Rating = 8,
                            Review = "Visit the Green Monster"
                        },
                        new
                        {
                            DestinationId = 7,
                            CityName = "Cairo",
                            CountryName = "Egypt",
                            Rating = 4,
                            Review = "The pyramids are smaller in real life"
                        },
                        new
                        {
                            DestinationId = 8,
                            CityName = "Johannesburg",
                            CountryName = "South Africa",
                            Rating = 8,
                            Review = "Swim with white sharks"
                        },
                        new
                        {
                            DestinationId = 9,
                            CityName = "Tokyo",
                            CountryName = "Japan",
                            Rating = 7,
                            Review = "Extremely lively city"
                        },
                        new
                        {
                            DestinationId = 10,
                            CityName = "Milan",
                            CountryName = "Italy",
                            Rating = 10,
                            Review = "Visit the duomo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
